In [2]:
import torch
import librosa
import os


In [1]:
from data_utils import create_dataloader

batch_size = 12
train_labels_path = './data/trial_labels.txt'
train_data_path = './data/train'
train_loader = create_dataloader(
    train_labels_path, train_data_path, batch_size)

no. files in  dataloader: 77


In [2]:
for batch, (X_train, y_train) in enumerate(train_loader):
    break



c:\Users\jieqi\Desktop\JQ\code_projects\audio_deepfake_detector\data_utils.py:56: UserWarning: PySoundFile failed. Trying audioread instead.
  X_raw, _ = librosa.load(
c:\Users\jieqi\Desktop\JQ\code_projects\audio_deepfake_detector\venv\Lib\site-packages\librosa\core\audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)


FileNotFoundError: [Errno 2] No such file or directory: './data/train/DF_E_2760644.flac'

In [3]:
X_train

NameError: name 'X_train' is not defined

In [7]:
start_time = time.time()

In [10]:
df[df['group'] == 'hidden'].groupby('label').count()

34560 * 0.01



345.6

In [2]:
import pandas as pd
df = pd.read_csv('./data/all_labels.txt',sep=' ', header=None)
df.rename(columns={1: 'key', 5: 'label', 7: 'group'},inplace=True)
df = df[['key','label','group']]

In [1]:
from data_utils import split_audio_dataset

split_audio_dataset()

found 32 flac file(s) in train directory...
transferring flac files back to train directory...
found 1200 flac file(s) in val directory...
transferring flac files back to train directory...
transferring new split of flac files to train data folder...
transferring new split of flac files to val data folder...
transferring new split of flac files to eval data folder...


In [ ]:
from librosa.feature import delta
import numpy as np
import librosa
import torch

SAMPLE_RATE = 16000
FRAME_SIZE = 2048
HOP_SIZE = int(FRAME_SIZE/4)

base_dir = './data/trial'
key = 'DF_E_2010009'
cut = 32300

def pad_random(x: np.ndarray, max_len: int = 64600):
    x_len = x.shape[0]
    # if duration is already long enough
    if x_len >= max_len:
        stt = np.random.randint(x_len - max_len)
        return x[stt:stt + max_len]

    # if too short
    num_repeats = int(max_len / x_len) + 1
    padded_x = np.tile(x, (num_repeats))[:max_len]
    return padded_x



X_raw, _ = librosa.load(
    str(f"{base_dir}/{key}.flac"), sr=SAMPLE_RATE)
X_pad = pad_random(X_raw, cut)
X_stft = librosa.stft(y=X_pad, n_fft=FRAME_SIZE, hop_length=HOP_SIZE)
X_log_stft = librosa.power_to_db(np.abs(X_stft)**2)
X_delta = librosa.feature.delta(X_log_stft, width=9, order=1)
X_delta2 = librosa.feature.delta(X_log_stft, width=9, order=2)
stacked = [arr.reshape((1, X_log_stft.shape[0], X_log_stft.shape[1]))
           for arr in (X_log_stft, X_delta, X_delta2)]
X = torch.FloatTensor(np.concatenate(stacked, axis=0))
print(X.shape)

C:\Users\jieqi\AppData\Local\Temp\ipykernel_12332\2765139466.py:29: UserWarning: PySoundFile failed. Trying audioread instead.
  X_raw, _ = librosa.load(
c:\Users\jieqi\Desktop\JQ\code_projects\audio_deepfake_detector\venv\Lib\site-packages\librosa\core\audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)


FileNotFoundError: [Errno 2] No such file or directory: './data/train/DF_E_2000011.flac'

In [7]:
import torch
test = torch.Tensor(1)


In [11]:
test.item()

-2.493218369655382e+35

In [9]:
def get_audio_log_stft(audio):
    
    audio_stft = librosa.stft(y=audio, n_fft=FRAME_SIZE, hop_length=HOP_SIZE)
    return librosa.power_to_db(audio_stft)
    

# Approach 1: STFT + CNN

In [8]:
audio, sr = librosa.load(f'{data_path}/{files[0]}',sr=SAMPLE_RATE)


C:\Users\jieqi\AppData\Local\Temp\ipykernel_22484\3564958598.py:1: UserWarning: PySoundFile failed. Trying audioread instead.
  audio, sr = librosa.load(f'{data_path}/{files[0]}',sr=SAMPLE_RATE)
c:\Users\jieqi\Desktop\JQ\code_projects\audio_deepfake_detector\venv\Lib\site-packages\librosa\core\audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)


# Approach 2: Raw Waveform Wav2Vec2

# Approach 3: Raw Waveform AAsist

# Approach 4: Raw Waveform Wav2Vec2 + AAsist

In [1]:
from data_utils import split_audio_dataset

split_audio_dataset()

transferring new split of flac files to train data folder...
transferring new split of flac files to val data folder...
transferring new split of flac files to eval data folder...


In [ ]:




# stft with librosa


# feed processed waveform to front_end_processor

inputs = front_end_processor(audio_log_stft, sampling_rate=sr, return_tensors="pt")

# feed frequency into
audio_cqt.shape

NameError: name 'np' is not defined

In [3]:
import numpy as np
np.random.randint(0)

ValueError: high <= 0

In [6]:
import torch
max_len = 5

stt = 0
x = torch.Tensor([1,2,3,4,5])
x[stt:stt + max_len]

tensor([1., 2., 3., 4., 5.])

In [3]:
from data_utils import split_audio_dataset

train_labels_file = './data/train_labels.txt'
train_dir = './data/train'
val_labels_file = './data/val_labels.txt'
val_dir = './data/val'


split_audio_dataset(train_labels_file, train_dir, val_labels_file, val_dir)

                 key  label
0       DF_E_2000011  spoof
1       DF_E_2000013  spoof
2       DF_E_2000024  spoof
3       DF_E_2000026  spoof
4       DF_E_2000027  spoof
...              ...    ...
491824  DF_E_4999945  spoof
491825  DF_E_4999962  spoof
491826  DF_E_4999964  spoof
491827  DF_E_4999980  spoof
491828  DF_E_4999993  spoof

[491829 rows x 2 columns]
transferring new split of flac files to destination directory...


In [1]:
import pandas as pd

In [14]:
df = pd.DataFrame(columns=['model','iteration', 'gpu', 'num_params', 'training_time', 'min_train_loss', 'min_val_loss', 'max_train_acc', 'max_val_acc', 'threshold', 'f1', 'recall', 'precision', 'eer'])


In [16]:
df.to_csv('./results/run_summary.csv',index=False)

In [2]:
import torch
    
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device: {}".format(device))
if device == "cpu":
    raise ValueError("GPU not detected!")

Device: cuda


In [13]:
torch.cuda.get_device_name()

'NVIDIA GeForce RTX 3050 Laptop GPU'

In [17]:
df = pd.DataFrame(columns=['col_1','col_2'])

In [26]:
data = {'col_1': 'asdas', 'col_2': 2}
pd.concat([df,pd.DataFrame.from_dict(data,orient='index').T],ignore_index=True)

col_1 col_2
0  asdas     2

In [24]:
import torch

batch_size = 3

my_tensor = torch.FloatTensor([[1,2],
                               [3,4],
                               [5,6]])


torch.masked_select(my_tensor, torch.BoolTensor([False,True]).repeat(batch_size,1))




tensor([2., 4., 6.])

In [25]:
my_tensor.shape

torch.Size([3, 2])

In [26]:
torch.Tensor([1,1,1,1,1]).view(-1)

tensor([1., 1., 1., 1., 1.])

In [34]:
correct_in_epoch = 0
predicted = torch.Tensor([0,1,1,1])
y_truth = torch.Tensor([0,0,0,1])
correct_in_epoch += (predicted == y_truth).sum()
print(correct_in_epoch)
    

tensor(2)


In [39]:
from models import SimpleCNN_STFT_FRAMESIZE_1024

model = SimpleCNN_STFT_FRAMESIZE_1024()

for layer in model.children():
   if hasattr(layer, 'reset_parameters'):
       layer.reset_parameters()

In [5]:
import os

len(os.listdir('./data/train'))/24

15492.875

In [41]:
import os
import shutil

src_dir = './data/trial'
destination_dir = './data/all'

for file in os.listdir(src_dir):
    shutil.move(f"{src_dir}/{file}", f"{destination_dir}/{file}")

In [42]:
import os
import shutil

df = pd.read_csv('./data/trial_labels.txt',sep=' ', names=['key','label'])

src_dir = './data/all'
destination_dir = './data/trial'

for file in df['key']:
    shutil.copy(f"{src_dir}/{file}.flac", f"{destination_dir}/{file}.flac")
    

In [26]:
torch.masked_select(y_val, torch.BoolTensor([False,True]).repeat(y_val.shape[0],1).to("cuda"))

In [22]:
import numpy as np


x = np.array([[1,2],[3,4],[5,6]])
mask = np.repeat([[False,True]],3,axis=0)
x[mask]


array([2, 4, 6])

In [30]:
y_truth = [0,0]
probs = np.array([[0.4,0.6],[0.6,0.4]])
preds = np.argmax(probs,axis=1)
total_correct_in_epoch = sum(preds == y_truth)
print(total_correct_in_epoch)




1


In [37]:
import os
import pandas as pd
import shutil

src_dir = './data/train'
destination_dir = './data/trial'

df = pd.read_csv('./data/trial_labels.txt',header=None,sep=' ')
df.rename(columns={0:'key',1:'label'},inplace=True)

for key in df['key']:
    shutil.copyfile(f'{src_dir}/{key}.flac',f'{destination_dir}/{key}.flac')


In [6]:
import pandas as pd

base_summary = pd.DataFrame(columns=['a', 'b', 'c', 'd'])
summary_stats = {'a': 1, 'b': 2, 'c': 3, 'd': 4}


final_summary = pd.concat([base_summary, pd.DataFrame.from_dict(
    summary_stats, orient='index').T], ignore_index=True)
final_summary = final_summary.fillna(0)
final_summary

C:\Users\jieqi\AppData\Local\Temp\ipykernel_14948\3145883929.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  final_summary = final_summary.fillna(0)


a  b  c  d
0  1  2  3  4